@echo off

set "LL_DEFAULT_SHM_NAME_PREFIX=latlink_%USERNAME%"
set "LL_DEFAULT_SHM_BUFFER_SIZE_BYTES=268435456"
set "LL_DEFAULT_PROTOCOL_VERSION=1"
set "LL_DEFAULT_HANDSHAKE_TIMEOUT_SEC=10"
set "LL_DEFAULT_AUTH_TOKEN=latlink_token_%USERNAME%"

set "LL_DEFAULT_MODEL_NAME=Qwen/Qwen2.5-3B-Instruct"
set "LL_DEFAULT_MODEL_REVISION=3ca5f5bff0f44b2b436a9aba99b900ab157c9a27"
set "LL_DEFAULT_PROMPT=hello"

set "LL_DEFAULT_BENCH_DURATION_SEC=60"
set "LL_DEFAULT_BENCH_TOKENS_PER_TURN=512"
set "LL_DEFAULT_BENCH_PROMPT=Subject: Explain how shared-memory KV cache teleportation compares to normal chat."
set "LL_DEFAULT_BENCH_SENDER_LOG=bench_latlink_sender.jsonl"
set "LL_DEFAULT_BENCH_RECEIVER_LOG=bench_latlink_receiver.jsonl"
set "LL_DEFAULT_BENCH_BASELINE_LOG=bench_baseline.jsonl"

set "LL_DEFAULT_BENCH_PAYLOAD_BYTES=1048576"
set "LL_DEFAULT_BENCH_SHM_SENDER_LOG=bench_shm_sender.jsonl"
set "LL_DEFAULT_BENCH_SHM_RECEIVER_LOG=bench_shm_receiver.jsonl"

set "LL_DEFAULT_BENCH_TCP_HOST=127.0.0.1"
set "LL_DEFAULT_BENCH_TCP_PORT=50051"
set "LL_DEFAULT_BENCH_TCP_SENDER_LOG=bench_tcp_sender.jsonl"
set "LL_DEFAULT_BENCH_TCP_RECEIVER_LOG=bench_tcp_receiver.jsonl"

if not defined LATLINK_SHM_NAME_PREFIX set "LATLINK_SHM_NAME_PREFIX=%LL_DEFAULT_SHM_NAME_PREFIX%"
if not defined LATLINK_SHM_BUFFER_SIZE_BYTES set "LATLINK_SHM_BUFFER_SIZE_BYTES=%LL_DEFAULT_SHM_BUFFER_SIZE_BYTES%"
if not defined LATLINK_PROTOCOL_VERSION set "LATLINK_PROTOCOL_VERSION=%LL_DEFAULT_PROTOCOL_VERSION%"
if not defined LATLINK_HANDSHAKE_TIMEOUT_SEC set "LATLINK_HANDSHAKE_TIMEOUT_SEC=%LL_DEFAULT_HANDSHAKE_TIMEOUT_SEC%"
if not defined LATLINK_AUTH_TOKEN set "LATLINK_AUTH_TOKEN=%LL_DEFAULT_AUTH_TOKEN%"

if not defined LATLINK_MODEL_NAME set "LATLINK_MODEL_NAME=%LL_DEFAULT_MODEL_NAME%"
if not defined LATLINK_MODEL_REVISION set "LATLINK_MODEL_REVISION=%LL_DEFAULT_MODEL_REVISION%"
if not defined LATLINK_PROMPT set "LATLINK_PROMPT=%LL_DEFAULT_PROMPT%"

if not defined LATLINK_BENCH_DURATION_SEC set "LATLINK_BENCH_DURATION_SEC=%LL_DEFAULT_BENCH_DURATION_SEC%"
if not defined LATLINK_BENCH_TOKENS_PER_TURN set "LATLINK_BENCH_TOKENS_PER_TURN=%LL_DEFAULT_BENCH_TOKENS_PER_TURN%"
if not defined LATLINK_BENCH_PROMPT set "LATLINK_BENCH_PROMPT=%LL_DEFAULT_BENCH_PROMPT%"
if not defined LATLINK_BENCH_SENDER_LOG set "LATLINK_BENCH_SENDER_LOG=%LL_DEFAULT_BENCH_SENDER_LOG%"
if not defined LATLINK_BENCH_RECEIVER_LOG set "LATLINK_BENCH_RECEIVER_LOG=%LL_DEFAULT_BENCH_RECEIVER_LOG%"
if not defined LATLINK_BENCH_BASELINE_LOG set "LATLINK_BENCH_BASELINE_LOG=%LL_DEFAULT_BENCH_BASELINE_LOG%"

if not defined LATLINK_BENCH_PAYLOAD_BYTES set "LATLINK_BENCH_PAYLOAD_BYTES=%LL_DEFAULT_BENCH_PAYLOAD_BYTES%"
if not defined LATLINK_BENCH_SHM_SENDER_LOG set "LATLINK_BENCH_SHM_SENDER_LOG=%LL_DEFAULT_BENCH_SHM_SENDER_LOG%"
if not defined LATLINK_BENCH_SHM_RECEIVER_LOG set "LATLINK_BENCH_SHM_RECEIVER_LOG=%LL_DEFAULT_BENCH_SHM_RECEIVER_LOG%"

if not defined LATLINK_BENCH_TCP_HOST set "LATLINK_BENCH_TCP_HOST=%LL_DEFAULT_BENCH_TCP_HOST%"
if not defined LATLINK_BENCH_TCP_PORT set "LATLINK_BENCH_TCP_PORT=%LL_DEFAULT_BENCH_TCP_PORT%"
if not defined LATLINK_BENCH_TCP_SENDER_LOG set "LATLINK_BENCH_TCP_SENDER_LOG=%LL_DEFAULT_BENCH_TCP_SENDER_LOG%"
if not defined LATLINK_BENCH_TCP_RECEIVER_LOG set "LATLINK_BENCH_TCP_RECEIVER_LOG=%LL_DEFAULT_BENCH_TCP_RECEIVER_LOG%"
